### PR TITLE
changed form from plural to singular

### PR DESCRIPTION
**Pull request by Amit-Goldblatt**
changed form from plural to singular, added inflect library and changed test form from plural to singular #9 .

### CODE REVIEW

**Comment by royashcenazi** [comment]
> changed form from plural to singular, added inflect library and changed test form from plural to singular #9 .

@Amit-Goldblatt thank you very much! 
Actually, there is an open PR for this issue made by @sigmagamma , but I suggested using `Inflect` in it
https://github.com/royashcenazi/parsigs/pull/9

LMK if you need assistance in finding another issue to contribute :)

**Comment by itay-goldraich** [comment]
#1

**Comment by royashcenazi** [comment]
@sigmagamma please fix conflicts, two minor comments and Ill merge :)

**Comment by royashcenazi** [comment]
Closing as there is a duplicate PR :) thanks @Amit-Goldblatt for inflect library

**Pull request closed without merging**
